INSERT INTO la_baunit_landsoilquality VALUES (1, 'Very good', 'Very good', true);
INSERT INTO la_baunit_landsoilquality VALUES (2, 'Moderate good', 'Moderate good', true);
INSERT INTO la_baunit_landsoilquality VALUES (3, 'Poor', 'Poor', true);
INSERT INTO la_baunit_landsoilquality VALUES (4, 'Very poor', 'Very poor', true);
SELECT pg_catalog.setval('la_baunit_landsoilquality_landsoilqualityid_seq', 4, true);

INSERT INTO la_baunit_landtype VALUES (1, 'Flat/Plain', 'Flat/Plain', true);
INSERT INTO la_baunit_landtype VALUES (2, 'Sloping', 'Sloping', true);
INSERT INTO la_baunit_landtype VALUES (3, 'Mountainous', 'Mountainous', true);
INSERT INTO la_baunit_landtype VALUES (4, 'Valley', 'Valley', true);
SELECT pg_catalog.setval('la_baunit_landtype_landtypeid_seq', 4, true);

INSERT INTO la_baunit_landusetype VALUES (1, 'Agriculture', 'Agriculture', true);
INSERT INTO la_baunit_landusetype VALUES (2, 'Pastoral', 'Pastoral', true);
INSERT INTO la_baunit_landusetype VALUES (3, 'Sylvicultural', 'Sylvicultural', true);
INSERT INTO la_baunit_landusetype VALUES (4, 'AquaCultural', 'AquaCultural', true);
INSERT INTO la_baunit_landusetype VALUES (5, 'Fauna', 'Fauna', true);
INSERT INTO la_baunit_landusetype VALUES (6, 'Others', 'Others', true);
SELECT pg_catalog.setval('la_baunit_landusetype_landusetypeid_seq', 6, true);

INSERT INTO la_ext_applicationstatus VALUES (1, 'New', 'New', true);
INSERT INTO la_ext_applicationstatus VALUES (2, 'Approved', 'Approved', true);
INSERT INTO la_ext_applicationstatus VALUES (3, 'Rejected', 'Rejected', true);
INSERT INTO la_ext_applicationstatus VALUES (4, 'Pending', 'Pending', true);
SELECT pg_catalog.setval('la_ext_applicationstatus_applicationstatusid_seq', 5, true);

INSERT INTO la_ext_attributecategory VALUES (1, 'General');
INSERT INTO la_ext_attributecategory VALUES (3, 'Tenure');
INSERT INTO la_ext_attributecategory VALUES (6, 'custom');
INSERT INTO la_ext_attributecategory VALUES (2, 'Multimedia');
INSERT INTO la_ext_attributecategory VALUES (4, 'Non Natural Person');
INSERT INTO la_ext_attributecategory VALUES (5, 'Natural Person');
INSERT INTO la_ext_attributecategory VALUES (7, 'General(Property)');
SELECT pg_catalog.setval('la_ext_attributecategory_attributecategoryid_seq', 1, false);

INSERT INTO la_ext_attributedatatype VALUES (1, 'String');
INSERT INTO la_ext_attributedatatype VALUES (3, 'Boolean');
INSERT INTO la_ext_attributedatatype VALUES (2, 'Date');
INSERT INTO la_ext_attributedatatype VALUES (4, 'Number');
INSERT INTO la_ext_attributedatatype VALUES (5, 'Dropdown');
SELECT pg_catalog.setval('la_ext_attributedatatype_datatypemasterid_seq', 1, false);

INSERT INTO la_ext_baselayer VALUES (1, 'Bing_Aerial', 'Bing_Aerial', true);
INSERT INTO la_ext_baselayer VALUES (2, 'Bing_Road', 'Bing_Road', true);
INSERT INTO la_ext_baselayer VALUES (3, 'Google_Hybrid', 'Google_Hybrid', true);
INSERT INTO la_ext_baselayer VALUES (4, 'Google_Physical', 'Google_Physical', true);
INSERT INTO la_ext_baselayer VALUES (5, 'Google_Satellite', 'Google_Satellite', true);
INSERT INTO la_ext_baselayer VALUES (6, 'Google_Streets', 'Google_Streets', true);
INSERT INTO la_ext_baselayer VALUES (7, 'MapQuest_OSM', 'MapQuest_OSM', true);
INSERT INTO la_ext_baselayer VALUES (8, 'Open_Street_Map', 'Open_Street_Map', true);
SELECT pg_catalog.setval('la_ext_baselayer_baselayerid_seq', 8, true);

INSERT INTO la_ext_disputestatus VALUES (1, 'Active', 'Active', true);
INSERT INTO la_ext_disputestatus VALUES (2, 'Resolved', 'Resolved', true);
SELECT pg_catalog.setval('la_ext_disputestatus_disputestatusid_seq', 2, true);

INSERT INTO la_ext_disputetype VALUES (1, 'Boundary', 'Boundary', true);
INSERT INTO la_ext_disputetype VALUES (2, 'Counter claim (Inter family)', 'Counter claim (Inter family)', true);
INSERT INTO la_ext_disputetype VALUES (3, 'Counter claim (Intra family)', 'Counter claim (Intra family)', true);
INSERT INTO la_ext_disputetype VALUES (4, 'Counter claim (Others)', 'Counter claim (Others)', true);
INSERT INTO la_ext_disputetype VALUES (5, 'Other interests', 'Other interests', true);
SELECT pg_catalog.setval('la_ext_disputetype_disputetypeid_seq', 5, true);

INSERT INTO la_ext_documentformat VALUES (1, 'image/gif', 'image/gif', true);
INSERT INTO la_ext_documentformat VALUES (2, 'image/jpeg', 'image/jpeg', true);
INSERT INTO la_ext_documentformat VALUES (3, 'image/png', 'image/png', true);
SELECT pg_catalog.setval('la_ext_documentformat_documentformatid_seq', 3, true);

INSERT INTO la_ext_documenttype VALUES (1, 'Informal Receipt of Sale', 'Informal Receipt of Sale', true);
INSERT INTO la_ext_documenttype VALUES (2, 'Formal Receipt of Sale', 'Formal Receipt of Sale', true);
INSERT INTO la_ext_documenttype VALUES (3, 'Letter of Allocation', 'Letter of Allocation', true);
INSERT INTO la_ext_documenttype VALUES (4, 'Probate Document', 'Probate Document', true);
INSERT INTO la_ext_documenttype VALUES (5, 'Other', 'Other', true);
SELECT pg_catalog.setval('la_ext_documenttype_documenttypeid_seq', 5, true);

INSERT INTO la_ext_grouptype VALUES (1, 'Civic', 'Civic', true);
INSERT INTO la_ext_grouptype VALUES (2, 'Mosque', 'Mosque', true);
INSERT INTO la_ext_grouptype VALUES (3, 'Association', 'Association', true);
INSERT INTO la_ext_grouptype VALUES (4, 'Cooperative', 'Cooperative', true);
INSERT INTO la_ext_grouptype VALUES (5, 'Informal', 'Informal', true);
INSERT INTO la_ext_grouptype VALUES (6, 'Other', 'Other', true);
SELECT pg_catalog.setval('la_ext_grouptype_grouptypeid_seq', 6, true);

INSERT INTO la_ext_layertype VALUES (1, 'WFS', 'WFS ', true);
INSERT INTO la_ext_layertype VALUES (2, 'WMS', 'WMS ', true);
SELECT pg_catalog.setval('la_ext_layertype_layertypeid_seq', 2, true);

INSERT INTO la_ext_module VALUES (1, 'Bookmark', 'Bookmark', '1', true);
INSERT INTO la_ext_module VALUES (2, 'Clear selection', 'Clear selection', '1', true);
INSERT INTO la_ext_module VALUES (3, 'Complaint', 'Complaint', '1', true);
INSERT INTO la_ext_module VALUES (4, 'Dynalayer', 'Dynalayer', '1', true);
INSERT INTO la_ext_module VALUES (5, 'Editing', 'Editing', '1', true);
INSERT INTO la_ext_module VALUES (6, 'Export', 'Export', '1', true);
INSERT INTO la_ext_module VALUES (7, 'File upload', 'File upload', '1', true);
INSERT INTO la_ext_module VALUES (8, 'Fixed zoom in', 'Fixed zoom in', '1', true);
INSERT INTO la_ext_module VALUES (9, 'Fixed zoom out', 'Fixed zoom out', '1', true);
INSERT INTO la_ext_module VALUES (10, 'Full view', 'Full view', '1', true);
INSERT INTO la_ext_module VALUES (11, 'Geoprocessing', 'Geoprocessing', '1', true);
INSERT INTO la_ext_module VALUES (12, 'Import data', 'Import data', '1', true);
INSERT INTO la_ext_module VALUES (13, 'Info', 'Info', '1', true);
INSERT INTO la_ext_module VALUES (14, 'Intersection', 'Intersection', '1', true);
INSERT INTO la_ext_module VALUES (15, 'Magnetic', 'Magnetic', '1', true);
INSERT INTO la_ext_module VALUES (16, 'Markup', 'Markup', '1', true);
INSERT INTO la_ext_module VALUES (17, 'Measure length', 'Measure length', '1', true);
INSERT INTO la_ext_module VALUES (18, 'Open project', 'Open project', '1', true);
INSERT INTO la_ext_module VALUES (19, 'Pan', 'Pan', '1', true);
INSERT INTO la_ext_module VALUES (20, 'Print', 'Print', '1', true);
INSERT INTO la_ext_module VALUES (21, 'Query', 'Query', '1', true);
INSERT INTO la_ext_module VALUES (22, 'Radiometric', 'Radiometric', '1', true);
INSERT INTO la_ext_module VALUES (23, 'Report', 'Report', '1', true);
INSERT INTO la_ext_module VALUES (24, 'Save project', 'Save project', '1', true);
INSERT INTO la_ext_module VALUES (25, 'Search', 'Search', '1', true);
INSERT INTO la_ext_module VALUES (26, 'Select box', 'Select box', '1', true);
INSERT INTO la_ext_module VALUES (27, 'Select feature', 'Select feature', '1', true);
INSERT INTO la_ext_module VALUES (28, 'Select polygon', 'Select polygon', '1', true);
INSERT INTO la_ext_module VALUES (29, 'Text style', 'Text style', '1', true);
INSERT INTO la_ext_module VALUES (30, 'Thematic', 'Thematic', '1', true);
INSERT INTO la_ext_module VALUES (31, 'Zoom in', 'Zoom in', '1', true);
INSERT INTO la_ext_module VALUES (32, 'Zoom next', 'Zoom next', '1', true);
INSERT INTO la_ext_module VALUES (33, 'Zoom out', 'Zoom out', '1', true);
INSERT INTO la_ext_module VALUES (34, 'Zoom previous', 'Zoom previous', '1', true);
INSERT INTO la_ext_module VALUES (35, 'Zoom to layer', 'Zoom to layer', '1', true);
INSERT INTO la_ext_module VALUES (36, 'Zoom to xy', 'Zoom to xy', '1', true);
SELECT pg_catalog.setval('la_ext_module_moduleid_seq', 36, true);

INSERT INTO la_ext_process VALUES (1, 'Lease', 'Lease', true);
INSERT INTO la_ext_process VALUES (2, 'Sale', 'Sale', true);
INSERT INTO la_ext_process VALUES (3, 'Mortgage', 'Mortgage', true);
SELECT pg_catalog.setval('la_ext_process_processid_seq', 3, true);

INSERT INTO la_ext_projection VALUES (1, 'EPSG:4326', 'EPSG:4326', true);
INSERT INTO la_ext_projection VALUES (2, 'EPSG:900913', 'EPSG:900913', true);
SELECT pg_catalog.setval('la_ext_projection_projectionid_seq', 1, false);

INSERT INTO la_ext_role VALUES (2, 'DPI', 'DPI', 'DPI Land Official', true);
INSERT INTO la_ext_role VALUES (3, 'PM', 'PM', 'Project Manager', true);
INSERT INTO la_ext_role VALUES (4, 'PUBLIC USER', 'PUBLIC USER', 'Public User', true);
INSERT INTO la_ext_role VALUES (5, 'SFR', 'SFR', 'SFR Land Official', true);
INSERT INTO la_ext_role VALUES (6, 'TRUSTED INTERMEDIARY', 'TRUSTED INTERMEDIARY', 'CFV Agent', true);
INSERT INTO la_ext_role VALUES (7, 'USER', 'USER', 'User', true);
INSERT INTO la_ext_role VALUES (1, 'ROLE_ADMIN', 'ADMIN', 'System Administrator', true);
SELECT pg_catalog.setval('la_ext_role_roleid_seq', 7, true);

INSERT INTO la_ext_unit VALUES (1, 'Foot', 'Foot', true);
INSERT INTO la_ext_unit VALUES (2, 'Inches ', 'Inches ', true);
INSERT INTO la_ext_unit VALUES (3, 'Kilometer', 'Kilometer', true);
INSERT INTO la_ext_unit VALUES (4, 'Meter', 'Meter', true);
INSERT INTO la_ext_unit VALUES (5, 'Miles', 'Miles', true);
INSERT INTO la_ext_unit VALUES (6, 'dd', 'dd', true);
SELECT pg_catalog.setval('la_ext_unit_unitid_seq', 5, true);

INSERT INTO la_partygroup_educationlevel VALUES (1, 'Primary', 'Primary', true);
INSERT INTO la_partygroup_educationlevel VALUES (2, 'Secondary', 'Secondary', true);
INSERT INTO la_partygroup_educationlevel VALUES (3, 'University', 'University', true);
INSERT INTO la_partygroup_educationlevel VALUES (4, 'Other', 'Other', true);
INSERT INTO la_partygroup_educationlevel VALUES (5, 'None', 'None', true);
SELECT pg_catalog.setval('la_partygroup_educationlevel_educationlevelid_seq', 5, true);

INSERT INTO la_partygroup_gender VALUES (1, 'Male', 'Male', true);
INSERT INTO la_partygroup_gender VALUES (2, 'Female', 'Female', true);
INSERT INTO la_partygroup_gender VALUES (3, 'Other', 'Other', true);
SELECT pg_catalog.setval('la_partygroup_gender_genderid_seq', 3, true);

INSERT INTO la_partygroup_identitytype VALUES (1, 'Voter ID', 'Voter ID', true);
INSERT INTO la_partygroup_identitytype VALUES (2, 'Driving license', 'Driving license', true);
INSERT INTO la_partygroup_identitytype VALUES (3, 'Passport', 'Passport', true);
INSERT INTO la_partygroup_identitytype VALUES (4, 'ID card', 'ID card', true);
INSERT INTO la_partygroup_identitytype VALUES (5, 'Other', 'Other', true);
INSERT INTO la_partygroup_identitytype VALUES (6, 'None', 'None', true);
SELECT pg_catalog.setval('la_partygroup_identitytype_identitytypeid_seq', 6, true);

INSERT INTO la_partygroup_maritalstatus VALUES (1, 'Single', 'Single', true);
INSERT INTO la_partygroup_maritalstatus VALUES (2, 'Married', 'Married', true);
INSERT INTO la_partygroup_maritalstatus VALUES (3, 'Divorced', 'Divorced', true);
INSERT INTO la_partygroup_maritalstatus VALUES (4, 'Widow', 'Widow', true);
INSERT INTO la_partygroup_maritalstatus VALUES (5, 'Widower', 'Widower', true);
SELECT pg_catalog.setval('la_partygroup_maritalstatus_maritalstatusid_seq', 5, true);

INSERT INTO la_partygroup_occupation VALUES (1, 'Government Employee', 'Government Employee', true);
INSERT INTO la_partygroup_occupation VALUES (2, 'Private Employee', 'Private Employee', true);
SELECT pg_catalog.setval('la_partygroup_occupation_occupationid_seq', 2, true);

INSERT INTO la_partygroup_persontype VALUES (1, 'Person (Natural)', 'Person (Natural)', true);
INSERT INTO la_partygroup_persontype VALUES (2, 'Organization (Non-Natural)', 'Organization (Non-Natural)', true);
INSERT INTO la_partygroup_persontype VALUES (3, 'Owner', 'Owner', true);
INSERT INTO la_partygroup_persontype VALUES (4, 'Guardian', 'Guardian', true);
INSERT INTO la_partygroup_persontype VALUES (5, 'Tenant', 'Tenant', true);
INSERT INTO la_partygroup_persontype VALUES (6, 'Administrator', 'Administrator', true);
SELECT pg_catalog.setval('la_partygroup_persontype_persontypeid_seq', 6, true);

INSERT INTO la_partygroup_relationshiptype VALUES (1, 'Father', 'Father', true);
INSERT INTO la_partygroup_relationshiptype VALUES (2, 'Mother', 'Mother', true);
INSERT INTO la_partygroup_relationshiptype VALUES (3, 'Sister', 'Sister', true);
INSERT INTO la_partygroup_relationshiptype VALUES (4, 'Brother', 'Brother', true);
INSERT INTO la_partygroup_relationshiptype VALUES (5, 'Son', 'Son', true);
INSERT INTO la_partygroup_relationshiptype VALUES (6, 'Daughter', 'Daughter', true);
INSERT INTO la_partygroup_relationshiptype VALUES (7, 'Grandmother', 'Grandmother', true);
INSERT INTO la_partygroup_relationshiptype VALUES (8, 'Grandfather', 'Grandfather', true);
INSERT INTO la_partygroup_relationshiptype VALUES (9, 'Grandson', 'Grandson', true);
INSERT INTO la_partygroup_relationshiptype VALUES (10, 'Granddaughter', 'Granddaughter', true);
INSERT INTO la_partygroup_relationshiptype VALUES (11, 'Uncle', 'Uncle', true);
INSERT INTO la_partygroup_relationshiptype VALUES (12, 'Aunt', 'Aunt', true);
INSERT INTO la_partygroup_relationshiptype VALUES (13, 'Niece', 'Niece', true);
INSERT INTO la_partygroup_relationshiptype VALUES (14, 'Nephew', 'Nephew', true);
INSERT INTO la_partygroup_relationshiptype VALUES (15, 'Other relatives', 'Other relatives', true);
INSERT INTO la_partygroup_relationshiptype VALUES (16, 'Partners', 'Partners', true);
INSERT INTO la_partygroup_relationshiptype VALUES (17, 'Other', 'Other', true);
INSERT INTO la_partygroup_relationshiptype VALUES (18, 'Spouses', 'Spouses', true);
INSERT INTO la_partygroup_relationshiptype VALUES (19, 'Parents and children', 'Parents and children', true);
INSERT INTO la_partygroup_relationshiptype VALUES (20, 'Siblings', 'Siblings', true);
SELECT pg_catalog.setval('la_partygroup_relationshiptype_relationshiptypeid_seq', 20, true);

INSERT INTO la_right_acquisitiontype VALUES (1, 'Kupewa na Halmashauri ya Kijiji', 'Allocated by Village Council', true);
INSERT INTO la_right_acquisitiontype VALUES (2, 'Zawadi', 'Gift', true);
INSERT INTO la_right_acquisitiontype VALUES (3, 'Urithi', 'Inheritance', true);
INSERT INTO la_right_acquisitiontype VALUES (4, 'Kununua', 'Purchase', true);
SELECT pg_catalog.setval('la_right_acquisitiontype_acquisitiontypeid_seq', 1, false);

INSERT INTO la_right_claimtype VALUES (1, 'Disputed claim', 'Disputed claim', true);
INSERT INTO la_right_claimtype VALUES (2, 'Existing right', 'Existing right', true);
INSERT INTO la_right_claimtype VALUES (3, 'New claim', 'New claim', true);
INSERT INTO la_right_claimtype VALUES (4, 'Unclaimed', 'Unclaimed', true);
SELECT pg_catalog.setval('la_right_claimtype_claimtypeid_seq', 1, false);

INSERT INTO la_right_landsharetype VALUES (1, 'Milki ya pamoja kwa Hisa', 'Co-occupancy (Tenancy in Common)', true);
INSERT INTO la_right_landsharetype VALUES (2, 'Milki ya mmoja', 'Single Occupant', true);
INSERT INTO la_right_landsharetype VALUES (3, 'Milki ya pamoja isiyogawanyika', 'Co-occupancy (Joint tenancy)', true);
SELECT pg_catalog.setval('la_right_landsharetype_landsharetypeid_seq', 1, false);

INSERT INTO la_right_tenureclass VALUES (1, 'Derivative Right', 'Derivative Right', true);
INSERT INTO la_right_tenureclass VALUES (2, 'Customary Right of Occupancy', 'Customary Right of Occupancy', true);
INSERT INTO la_right_tenureclass VALUES (3, 'Cerificate of Occupany', 'Cerificate of Occupany', true);
INSERT INTO la_right_tenureclass VALUES (4, 'Right of Use', 'Right of Use', true);
INSERT INTO la_right_tenureclass VALUES (5, 'Formal Ownership (Free-hold)', 'Formal Ownership (Free-hold)', true);
SELECT pg_catalog.setval('la_right_tenureclass_tenureclassid_seq', 1, true);

INSERT INTO la_spatialunitgroup VALUES (1, 'Country', 'Country', true);
INSERT INTO la_spatialunitgroup VALUES (2, 'Region', 'Region', true);
INSERT INTO la_spatialunitgroup VALUES (3, 'Province', 'Province', true);
INSERT INTO la_spatialunitgroup VALUES (4, 'Commune', 'Commune', true);
INSERT INTO la_spatialunitgroup VALUES (5, 'Place', 'Place', true);
SELECT pg_catalog.setval('la_spatialunitgroup_spatialunitgroupid_seq', 6, true);

INSERT INTO la_spatialunitgroup_hierarchy VALUES (3, 'Balé', 'Balé', 3, 2, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (9, 'Bagassi', 'Bagassi', 4, 3, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (10, 'Bana', 'Bana', 4, 3, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (11, 'Boromo', 'Boromo', 4, 3, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (12, 'Fara', 'Fara', 4, 3, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (13, 'Ouri', 'Ouri', 4, 3, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (14, 'Pa', 'Pa', 4, 3, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (2, 'Boucle du Mouhoun', 'Boucle du Mouhoun', 2, 1, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (4, 'Banwa', 'Banwa', 3, 2, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (56, 'Assio', 'Assio', 5, 9, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (57, 'Bagassi', 'Bagassi', 5, 9, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (58, 'Bandio', 'Bandio', 5, 9, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (59, 'Bounou', 'Bounou', 5, 9, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (60, 'Doussi', 'Doussi', 5, 9, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (61, 'Haho', 'Haho', 5, 9, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (62, 'Heredougou', 'Heredougou', 5, 9, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (63, 'Kahin', 'Kahin', 5, 9, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (64, 'Kaho', 'Kaho', 5, 9, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (65, 'Koussaro', 'Koussaro', 5, 9, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (66, 'Niaga', 'Niaga', 5, 9, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (67, 'Niakongo', 'Niakongo', 5, 9, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (68, 'Pahin', 'Pahin', 5, 9, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (69, 'Sipohin', 'Sipohin', 5, 9, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (70, 'Yaramoko', 'Yaramoko', 5, 9, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (71, 'Bassana', 'Bassana', 5, 10, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (72, 'Ouona', 'Ouona', 5, 10, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (73, 'Soma', 'Soma', 5, 10, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (74, 'Boromo    ', 'Boromo    ', 5, 11, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (75, 'Kalanbouli    ', 'Kalanbouli    ', 5, 11, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (76, 'Nanou    ', 'Nanou    ', 5, 11, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (77, 'Ouahabou    ', 'Ouahabou    ', 5, 11, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (78, 'Ouroubono    ', 'Ouroubono    ', 5, 11, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (79, 'Petit Balé    ', 'Petit Balé    ', 5, 11, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (80, 'Virou ', 'Virou ', 5, 11, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (81, 'Bilatio', 'Bilatio', 5, 12, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (82, 'Bouzourou', 'Bouzourou', 5, 12, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (83, 'Daho', 'Daho', 5, 12, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (84, 'Fitien', 'Fitien', 5, 12, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (85, 'Kabourou', 'Kabourou', 5, 12, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (86, 'Kapa', 'Kapa', 5, 12, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (87, 'Karaba', 'Karaba', 5, 12, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (88, 'Konzena', 'Konzena', 5, 12, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (89, 'Koundi', 'Koundi', 5, 12, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (90, 'Laro', 'Laro', 5, 12, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (91, 'Nanano', 'Nanano', 5, 12, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (92, 'Lasso', 'Lasso', 5, 13, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (93, 'Oury', 'Oury', 5, 13, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (94, 'Seyou', 'Seyou', 5, 13, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (95, 'Siou', 'Siou', 5, 13, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (96, 'Soubouy', 'Soubouy', 5, 13, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (97, 'Boro', 'Boro', 5, 14, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (98, 'Pa', 'Pa', 5, 14, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (1, 'Burkina Faso', 'Burkina Faso', 1, NULL, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (5, 'Kossi', 'Kossi', 3, 2, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (6, 'Mouhoun', 'Mouhoun', 3, 2, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (7, 'Nayala', 'Nayala', 3, 2, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (8, 'Sourou', 'Sourou', 3, 2, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (15, 'Pompoi', 'Pompoi', 4, 3, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (16, 'Poura', 'Poura', 4, 3, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (17, 'Siby', 'Siby', 4, 3, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (18, 'Yaho', 'Yaho', 4, 3, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (19, 'Balavé', 'Balavé', 4, 4, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (20, 'Kouka', 'Kouka', 4, 4, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (21, 'Sami', 'Sami', 4, 4, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (22, 'Sanaba', 'Sanaba', 4, 4, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (23, 'Solenzo', 'Solenzo', 4, 4, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (24, 'Tansila', 'Tansila', 4, 4, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (25, 'Barani', 'Barani', 4, 5, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (26, 'Bomborokui', 'Bomborokui', 4, 5, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (27, 'Bourasso', 'Bourasso', 4, 5, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (28, 'Djibasso', 'Djibasso', 4, 5, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (29, 'Dokui', 'Dokui', 4, 5, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (30, 'Doumbala', 'Doumbala', 4, 5, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (31, 'Kombori', 'Kombori', 4, 5, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (32, 'Madouba', 'Madouba', 4, 5, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (33, 'Nouna', 'Nouna', 4, 5, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (34, 'Sono', 'Sono', 4, 5, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (35, 'Bondoukui', 'Bondoukui', 4, 6, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (36, 'Dédougou', 'Dédougou', 4, 6, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (37, 'Douroula', 'Douroula', 4, 6, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (38, 'Kona', 'Kona', 4, 6, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (39, 'Ouarkoye', 'Ouarkoye', 4, 6, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (40, 'Safane', 'Safane', 4, 6, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (41, 'Tchériba', 'Tchériba', 4, 6, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (42, 'Gassan', 'Gassan', 4, 7, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (43, 'Gossina', 'Gossina', 4, 7, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (44, 'Kougny', 'Kougny', 4, 7, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (45, 'Toma', 'Toma', 4, 7, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (46, 'Yaba', 'Yaba', 4, 7, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (47, 'Yé', 'Yé', 4, 7, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (48, 'Di', 'Di', 4, 8, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (49, 'Gomboro', 'Gomboro', 4, 8, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (50, 'Kassoum', 'Kassoum', 4, 8, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (51, 'Kiémbara', 'Kiémbara', 4, 8, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (52, 'Lanfiéra', 'Lanfiéra', 4, 8, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (53, 'Lankoué', 'Lankoué', 4, 8, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (54, 'Toéni', 'Toéni', 4, 8, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (55, 'Tougan', 'Tougan', 4, 8, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (99, 'Voho', 'Voho', 5, 14, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (100, 'Konkoliko', 'Konkoliko', 5, 15, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (101, 'Pompoi', 'Pompoi', 5, 15, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (102, 'San', 'San', 5, 15, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (103, 'Poura', 'Poura', 5, 16, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (104, 'Bitiako', 'Bitiako', 5, 17, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (105, 'Ouako', 'Ouako', 5, 17, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (106, 'Siby', 'Siby', 5, 17, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (107, 'Bondo', 'Bondo', 5, 18, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (108, 'Fobiri', 'Fobiri', 5, 18, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (109, 'Mamou', 'Mamou', 5, 18, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (110, 'Maoula', 'Maoula', 5, 18, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (111, 'Yaho', 'Yaho', 5, 18, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (112, 'Balawé', 'Balawé', 5, 19, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (113, 'Tangouna', 'Tangouna', 5, 19, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (114, 'Yasso', 'Yasso', 5, 19, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (115, 'Diontala', 'Diontala', 5, 20, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (116, 'Fini', 'Fini', 5, 20, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (117, 'Kotou', 'Kotou', 5, 20, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (118, 'Kouka', 'Kouka', 5, 20, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (119, 'Liaba', 'Liaba', 5, 20, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (120, 'Sama', 'Sama', 5, 20, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (121, 'Dima', 'Dima', 5, 21, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (122, 'Sami', 'Sami', 5, 21, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (123, 'Bendougou', 'Bendougou', 5, 22, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (124, 'Founa', 'Founa', 5, 22, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (125, 'Koba', 'Koba', 5, 22, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (126, 'Kossoba', 'Kossoba', 5, 22, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (127, 'Nemena', 'Nemena', 5, 22, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (128, 'Ouarakuy', 'Ouarakuy', 5, 22, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (129, 'Pekuy', 'Pekuy', 5, 22, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (130, 'Sanaba', 'Sanaba', 5, 22, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (131, 'Béna', 'Béna', 5, 23, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (132, 'Daboura', 'Daboura', 5, 23, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (133, 'Denkoro', 'Denkoro', 5, 23, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (134, 'Dira', 'Dira', 5, 23, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (135, 'Dissankuy', 'Dissankuy', 5, 23, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (136, 'Masso', 'Masso', 5, 23, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (137, 'Moussakongo', 'Moussakongo', 5, 23, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (138, 'Solenzo', 'Solenzo', 5, 23, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (139, 'Ben', 'Ben', 5, 23, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (140, 'Dema', 'Dema', 5, 24, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (141, 'Nangouna', 'Nangouna', 5, 24, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (142, 'Tansila', 'Tansila', 5, 24, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (143, 'Barani', 'Barani', 5, 25, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (144, 'Berma', 'Berma', 5, 25, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (145, 'Boulemporo', 'Boulemporo', 5, 25, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (146, 'Diallo', 'Diallo', 5, 25, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (147, 'Illa', 'Illa', 5, 25, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (148, 'Kolonkan Goure Ba', 'Kolonkan Goure Ba', 5, 25, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (149, 'Konkoro', 'Konkoro', 5, 25, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (150, 'Mantamou', 'Mantamou', 5, 25, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (151, 'Nabasso', 'Nabasso', 5, 25, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (152, 'Niako', 'Niako', 5, 25, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (153, 'Sisse', 'Sisse', 5, 25, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (154, 'Soudogo', 'Soudogo', 5, 25, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (155, 'Tira', 'Tira', 5, 25, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (156, 'Torokoto', 'Torokoto', 5, 25, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (157, 'Yalankoro', 'Yalankoro', 5, 25, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (158, 'Yallo', 'Yallo', 5, 26, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (159, 'Bagala', 'Bagala', 5, 27, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (160, 'Bourasso', 'Bourasso', 5, 27, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (161, 'Kerena', 'Kerena', 5, 27, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (162, 'Kodougou', 'Kodougou', 5, 27, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (163, 'Labarani', 'Labarani', 5, 27, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (164, 'Lemini', 'Lemini', 5, 27, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (165, 'Sikoro', 'Sikoro', 5, 27, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (166, 'Ba', 'Ba', 5, 28, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (167, 'Banana', 'Banana', 5, 28, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (168, 'Bokoro', 'Bokoro', 5, 28, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (169, 'Diena', 'Diena', 5, 28, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (170, 'Djibasso', 'Djibasso', 5, 28, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (171, 'Donkoro', 'Donkoro', 5, 28, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (172, 'Ira', 'Ira', 5, 28, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (173, 'Kolonzo', 'Kolonzo', 5, 28, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (174, 'Senoulo', 'Senoulo', 5, 28, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (175, 'Voro', 'Voro', 5, 28, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (176, 'Ayoubakolon', 'Ayoubakolon', 5, 29, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (177, 'Dokuy', 'Dokuy', 5, 29, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (178, 'Goni', 'Goni', 5, 29, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (179, 'Karasso', 'Karasso', 5, 29, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (180, 'Nereko', 'Nereko', 5, 29, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (181, 'Toni', 'Toni', 5, 29, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (182, 'Doumbala', 'Doumbala', 5, 30, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (183, 'Kini-Kini', 'Kini-Kini', 5, 30, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (184, 'Teni', 'Teni', 5, 30, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (185, 'Wa', 'Wa', 5, 30, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (186, 'Lonani', 'Lonani', 5, 31, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (187, 'Sanakadougou', 'Sanakadougou', 5, 31, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (188, 'Siekoro', 'Siekoro', 5, 31, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (189, 'Siewali', 'Siewali', 5, 31, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (190, 'Kolokan', 'Kolokan', 5, 32, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (191, 'Yourouna', 'Yourouna', 5, 32, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (192, 'Bisso', 'Bisso', 5, 33, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (193, 'Damandigui', 'Damandigui', 5, 33, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (194, 'Dara', 'Dara', 5, 33, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (195, 'Dembo', 'Dembo', 5, 33, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (196, 'Dina', 'Dina', 5, 33, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (197, 'Diondougou', 'Diondougou', 5, 33, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (198, 'Karekuy', 'Karekuy', 5, 33, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (199, 'Konankoira', 'Konankoira', 5, 33, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (200, 'Lei', 'Lei', 5, 33, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (201, 'Mourdie', 'Mourdie', 5, 33, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (202, 'Nouna', 'Nouna', 5, 33, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (203, 'Seriba', 'Seriba', 5, 33, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (204, 'Sobon', 'Sobon', 5, 33, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (205, 'Soin', 'Soin', 5, 33, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (206, 'Tenou', 'Tenou', 5, 33, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (207, 'Tonkoroni', 'Tonkoroni', 5, 33, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (208, 'Sono', 'Sono', 5, 34, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (209, 'Bondoukuy', 'Bondoukuy', 5, 35, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (210, 'Dampan', 'Dampan', 5, 35, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (211, 'Kera', 'Kera', 5, 35, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (212, 'Koumana', 'Koumana', 5, 35, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (213, 'Ouakara', 'Ouakara', 5, 35, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (214, 'Syn bekuy', 'Syn bekuy', 5, 35, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (215, 'Tankuy', 'Tankuy', 5, 35, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (216, 'Tia', 'Tia', 5, 35, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (217, 'Toun', 'Toun', 5, 35, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (218, 'Apirikiti', 'Apirikiti', 5, 36, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (219, 'Dedougou', 'Dedougou', 5, 36, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (220, 'Fakouna', 'Fakouna', 5, 36, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (221, 'Kamanbera', 'Kamanbera', 5, 36, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (222, 'Kamandena', 'Kamandena', 5, 36, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (223, 'Kari', 'Kari', 5, 36, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (224, 'Kassakongo', 'Kassakongo', 5, 36, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (225, 'Koran', 'Koran', 5, 36, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (226, 'Kore', 'Kore', 5, 36, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (227, 'Koukatenga', 'Koukatenga', 5, 36, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (228, 'Massala', 'Massala', 5, 36, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (229, 'Oulani', 'Oulani', 5, 36, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (230, 'Parade', 'Parade', 5, 36, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (231, 'Passakongo', 'Passakongo', 5, 36, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (232, 'Sagala', 'Sagala', 5, 36, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (233, 'Soukuy', 'Soukuy', 5, 36, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (234, 'Souri', 'Souri', 5, 36, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (235, 'Wetina', 'Wetina', 5, 36, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (236, 'Zakuy', 'Zakuy', 5, 36, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (237, 'Zeoula', 'Zeoula', 5, 36, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (238, 'Zeoule', 'Zeoule', 5, 36, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (239, 'Douroula', 'Douroula', 5, 37, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (240, 'Kankono', 'Kankono', 5, 37, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (241, 'Karo', 'Karo', 5, 37, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (242, 'Kirikongo', 'Kirikongo', 5, 37, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (243, 'Sa', 'Sa', 5, 37, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (244, 'Toroba', 'Toroba', 5, 37, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (245, 'Dangouna', 'Dangouna', 5, 38, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (246, 'Goulo', 'Goulo', 5, 38, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (247, 'Kona', 'Kona', 5, 38, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (248, 'Lah', 'Lah', 5, 38, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (249, 'Nana', 'Nana', 5, 38, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (250, 'Sanfle', 'Sanfle', 5, 38, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (251, 'Tona', 'Tona', 5, 38, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (252, 'Yoana', 'Yoana', 5, 38, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (253, 'Zina', 'Zina', 5, 38, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (254, 'Bekuy', 'Bekuy', 5, 39, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (255, 'Darou', 'Darou', 5, 39, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (256, 'Fakena', 'Fakena', 5, 39, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (257, 'Kamako', 'Kamako', 5, 39, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (258, 'Kekaba', 'Kekaba', 5, 39, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (259, 'Kosso', 'Kosso', 5, 39, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (260, 'Lokinde', 'Lokinde', 5, 39, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (261, 'Miana', 'Miana', 5, 39, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (262, 'Monkuy', 'Monkuy', 5, 39, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (263, 'Ouarkoy', 'Ouarkoy', 5, 39, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (264, 'Oubli du E', 'Oubli du E', 5, 39, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (265, 'Poundou', 'Poundou', 5, 39, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (266, 'Soana', 'Soana', 5, 39, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (267, 'Biforo', 'Biforo', 5, 40, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (268, 'Bilakongo', 'Bilakongo', 5, 40, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (269, 'Bossien', 'Bossien', 5, 40, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (270, 'Datomo', 'Datomo', 5, 40, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (271, 'Kira', 'Kira', 5, 40, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (272, 'Kokoun', 'Kokoun', 5, 40, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (273, 'Kongosso', 'Kongosso', 5, 40, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (274, 'Makongo', 'Makongo', 5, 40, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (275, 'Nounou', 'Nounou', 5, 40, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (276, 'Pakoro', 'Pakoro', 5, 40, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (277, 'Safane', 'Safane', 5, 40, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (278, 'Sikorosso', 'Sikorosso', 5, 40, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (279, 'Sirakorosso', 'Sirakorosso', 5, 40, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (280, 'Sodien', 'Sodien', 5, 40, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (281, 'Tiekuy', 'Tiekuy', 5, 40, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (282, 'Yamou', 'Yamou', 5, 40, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (283, 'Yankasso', 'Yankasso', 5, 40, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (284, 'Yankoro', 'Yankoro', 5, 40, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (285, 'Ziasso', 'Ziasso', 5, 40, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (286, 'Bissanderou', 'Bissanderou', 5, 41, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (287, 'Douroukou', 'Douroukou', 5, 41, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (288, 'Labien', 'Labien', 5, 41, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (289, 'Saho', 'Saho', 5, 41, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (290, 'Tigan', 'Tigan', 5, 41, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (291, 'Tikan', 'Tikan', 5, 41, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (292, 'Youlou', 'Youlou', 5, 41, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (293, 'Djimbara', 'Djimbara', 5, 42, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (294, 'Gassan', 'Gassan', 5, 42, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (295, 'Soni', 'Soni', 5, 42, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (296, 'Soroni', 'Soroni', 5, 42, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (297, 'Toubani', 'Toubani', 5, 42, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (298, 'Warou', 'Warou', 5, 42, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (299, 'Zaba', 'Zaba', 5, 42, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (300, 'Boun', 'Boun', 5, 43, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (301, 'Gossina', 'Gossina', 5, 43, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (302, 'Kalabo', 'Kalabo', 5, 43, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (303, 'Koayo', 'Koayo', 5, 43, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (304, 'Kwon', 'Kwon', 5, 43, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (305, 'Madamao', 'Madamao', 5, 43, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (306, 'Massako', 'Massako', 5, 43, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (307, 'Naboro', 'Naboro', 5, 43, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (308, 'Sui', 'Sui', 5, 43, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (309, 'Tandou', 'Tandou', 5, 43, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (310, 'Youloupo', 'Youloupo', 5, 43, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (311, 'Goin', 'Goin', 5, 44, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (312, 'Kamba', 'Kamba', 5, 44, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (313, 'Kibiri', 'Kibiri', 5, 44, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (314, 'Nimina', 'Nimina', 5, 44, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (315, 'Goa', 'Goa', 5, 45, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (316, 'Koin', 'Koin', 5, 45, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (317, 'Nyon', 'Nyon', 5, 45, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (318, 'Raotenga', 'Raotenga', 5, 45, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (319, 'Sawa', 'Sawa', 5, 45, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (320, 'Semba', 'Semba', 5, 45, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (321, 'Toma', 'Toma', 5, 45, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (322, 'Biba', 'Biba', 5, 46, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (323, 'Biena', 'Biena', 5, 46, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (324, 'Logue', 'Logue', 5, 46, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (325, 'Pangogo', 'Pangogo', 5, 46, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (326, 'Sapala', 'Sapala', 5, 46, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (327, 'Saran', 'Saran', 5, 46, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (328, 'Siena', 'Siena', 5, 46, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (329, 'Tiema', 'Tiema', 5, 46, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (330, 'Toba', 'Toba', 5, 46, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (331, 'Yaba', 'Yaba', 5, 46, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (332, 'Goersa', 'Goersa', 5, 47, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (333, 'Massala', 'Massala', 5, 47, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (334, 'Niempourou', 'Niempourou', 5, 47, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (335, 'Saoura', 'Saoura', 5, 47, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (336, 'Touri', 'Touri', 5, 47, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (337, 'Yé', 'Yé', 5, 47, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (338, 'Debe', 'Debe', 5, 48, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (339, 'Di', 'Di', 5, 48, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (340, 'Donon', 'Donon', 5, 48, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (341, 'Niassan', 'Niassan', 5, 48, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (342, 'Niassari', 'Niassari', 5, 48, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (343, 'Poro', 'Poro', 5, 48, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (344, 'Tourou', 'Tourou', 5, 48, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (345, 'Touroukoro', 'Touroukoro', 5, 48, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (346, 'Bambara', 'Bambara', 5, 49, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (347, 'Gala', 'Gala', 5, 49, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (348, 'Gomboro', 'Gomboro', 5, 49, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (349, 'Bao', 'Bao', 5, 50, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (350, 'Bonro', 'Bonro', 5, 50, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (351, 'Dianra', 'Dianra', 5, 50, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (352, 'Douban', 'Douban', 5, 50, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (353, 'Doussoula', 'Doussoula', 5, 50, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (354, 'Kassoum', 'Kassoum', 5, 50, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (355, 'Kourani', 'Kourani', 5, 50, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (356, 'Pini', 'Pini', 5, 50, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (357, 'Sorona', 'Sorona', 5, 50, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (358, 'Soumarani', 'Soumarani', 5, 50, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (359, 'Tianra', 'Tianra', 5, 50, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (360, 'Tiao', 'Tiao', 5, 50, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (361, 'Gan', 'Gan', 5, 51, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (362, 'Kiembara', 'Kiembara', 5, 51, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (363, 'Kirio', 'Kirio', 5, 51, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (364, 'Niassono', 'Niassono', 5, 51, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (365, 'Bissan', 'Bissan', 5, 52, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (366, 'Gouran', 'Gouran', 5, 52, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (367, 'Kamina', 'Kamina', 5, 52, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (368, 'Kamona', 'Kamona', 5, 52, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (369, 'Lanfiera', 'Lanfiera', 5, 52, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (370, 'Toumani', 'Toumani', 5, 52, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (371, 'Unknown', 'Unknown', 5, 52, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (372, 'Lankoué', 'Lankoué', 5, 53, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (373, 'Dagale', 'Dagale', 5, 54, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (374, 'Domoni', 'Domoni', 5, 54, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (375, 'Dounkou', 'Dounkou', 5, 54, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (376, 'Ganagoulo', 'Ganagoulo', 5, 54, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (377, 'Gome', 'Gome', 5, 54, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (378, 'Loroni', 'Loroni', 5, 54, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (379, 'Louta', 'Louta', 5, 54, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (380, 'Nehourou', 'Nehourou', 5, 54, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (381, 'Seme', 'Seme', 5, 54, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (382, 'Sindie', 'Sindie', 5, 54, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (383, 'Boussoum', 'Boussoum', 5, 55, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (384, 'Daka', 'Daka', 5, 55, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (385, 'Diouroum', 'Diouroum', 5, 55, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (386, 'Dissi', 'Dissi', 5, 55, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (387, 'Gorombouli', 'Gorombouli', 5, 55, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (388, 'Goron', 'Goron', 5, 55, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (389, 'Gosson', 'Gosson', 5, 55, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (390, 'Kassan', 'Kassan', 5, 55, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (391, 'Kouy', 'Kouy', 5, 55, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (392, 'Largogo', 'Largogo', 5, 55, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (393, 'Nassan', 'Nassan', 5, 55, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (394, 'Niankore', 'Niankore', 5, 55, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (395, 'Rabouglitenga', 'Rabouglitenga', 5, 55, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (396, 'Tougan', 'Tougan', 5, 55, true);
INSERT INTO la_spatialunitgroup_hierarchy VALUES (397, 'Toungare', 'Toungare', 5, 55, true);
SELECT pg_catalog.setval('la_spatialunitgroup_hierarchy_hierarchyid_seq', 398, true);


